# Generated by Django 3.2.15 on 2022-08-30 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(db_column='descricao', on_delete=django.db.models.deletion.CASCADE, to='caixa.comida')),
            ],
        ),
    ]
