# Generated by Django 3.2.15 on 2022-08-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
