# Generated by Django 3.2.15 on 2022-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_pedidos_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item1',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], default=('M', 'Masculino'), max_length=30),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=1),
        ),
    ]
