# Generated by Django 3.2.15 on 2022-08-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_auto_20220830_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='item2',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item3',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item4',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item5',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item6',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item7',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item8',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item9',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item2',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item3',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item4',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item5',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item6',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item7',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item8',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='qtd_item9',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='item1',
            field=models.CharField(choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], default=('arroz', 'arroz'), max_length=30),
        ),
    ]
