# Generated by Django 3.2.15 on 2022-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_auto_20220830_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='item2',
            field=models.CharField(blank=True, choices=[('arroz', 'arroz'), ('feijão', 'feijão'), ('macarrão', 'macarrão')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='qtd_item2',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
    ]
